<?php
/** @var $escaper \Magento\Framework\Escaper */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;

$ruleProvider = $this->helper('\Fastly\Cdn\Model\Ngwaf\RuleProvider');
$rulePayload = $ruleProvider->getPayload();

$getRulesUrl = $block->getUrl('adminhtml/fastlyCdn_Ngwaf/getAllRules');
$deleteRuleUrl = $block->getUrl('adminhtml/fastlyCdn_Ngwaf/deleteRule');
$editRuleUrl = $block->getUrl('adminhtml/fastlyCdn_Ngwaf/editRule');
$getRuleSelectOptionsUrl = $block->getUrl('adminhtml/fastlyCdn_Ngwaf/getRuleSelectOptions');
?>

<div id="grid<?= $escaper->escapeHtmlAttr($_htmlId); ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= $escaper->escapeHtmlAttr($block->getElement()->getId()); ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                    <th><?= $escaper->escapeHtml($column['label']); ?></th>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?= $escaper->escapeHtmlAttr($_colspan); ?>">Action</th>
            </tr>
            </thead>
            <tbody id="fastly-rules-list"></tbody>
        </table>
    </div>
    <p id="ngwaf-loading-rules" class="list-loading">
        <img class="ngwaf-processing"
             alt="Collecting"
             style="margin:0 5px;"
             src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Fastly_Cdn::images/fastly16.gif')) ?>" />
        <?= $escaper->escapeHtml('Loading rules...'); ?>
    </p>
    <p id="ngwaf-no-rules" class="no-rules" style="display: none;">
        <?= $escaper->escapeHtml('No custom rules found.'); ?>
    </p>
</div>

<div class="message message-error fastly-button-messages"
     id="fastly-error-ngwaf-rule"
     style="display: none">
</div>
<div class="message message-success fastly-button-messages"
     id="fastly-success-ngwaf-rule"
     style="display: none">
</div>


<div id="fastly-rule-modal-content">
    <div class="modal-inner-content">
    </div>
</div>

<!-- Custom Rule creation/edit template -->
<script type="text/x-magento-template" id="fastly-custom-rule-template">

    <form action="<?= $editRuleUrl?>"
          method="POST"
          id="fastly-custom-rule-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="fastly_ngwaf_rule_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Rule type") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="fastly_ngwaf_rule_type" id="fastly_ngwaf_rule_type" class="admin__control-text">
                    </select>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="fastly_ngwaf_rule_condition_match_operator" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Rule applies if X conditions are true") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="fastly_ngwaf_rule_condition_match_operator" id="fastly_ngwaf_rule_condition_match_operator" class="admin__control-text">
                        <option value="all" selected>All</option>
                        <option value="any">Any</option>
                    </select>
                </div>
            </div>

            <h2><?php /* @noEscape */ echo __("Conditions") ?></h2>
            <div class="ngwaf-conditions">
                <div class="ngwaf-condition" style="display: flex">
                    <div class="admin__field field _required" style="flex: 1">
                        <label class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Field") ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select name="fastly_ngwaf_rule_condition_field[]" class="admin__control-text fastly_ngwaf_rule_condition_field">
                            </select>
                        </div>
                    </div>
                    <div class="admin__field field _required" style="flex: 1">
                        <label class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Operator") ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select name="fastly_ngwaf_rule_condition_operator[]" class="admin__control-text fastly_ngwaf_rule_condition_operator">
                            </select>
                        </div>
                    </div>
                    <div class="admin__field field _required" style="flex: 1">
                        <label class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Value") ?></span>
                        </label>
                        <div class="admin__field-control condition-input">
                            <input type="text"
                                   name="fastly_ngwaf_rule_condition_value[]"
                                   required="required"
                                   class="admin__control-text required-entry fastly_ngwaf_rule_condition_value">
                        </div>
                        <div class="admin__field-control condition-select">
                            <select name="fastly_ngwaf_rule_condition_value[]"
                                    class="admin__control-text required-entry fastly_ngwaf_rule_condition_value"
                                    required="required">
                            </select>
                        </div>
                    </div>
                    <button class='action-delete fastly-delete-snippet-icon ngwaf-fastly-delete-rule-condition-action'
                            title='Delete Condition'
                            type='button'></button>
                </div>

                <button class='ngwaf-fastly-add-rule-condition-action'
                        title='Add Condition'
                        type='button'>Add condition</button>

                <button class='ngwaf-fastly-add-rule-condition-group-action'
                        title='Add Group'
                        type='button'>Add Group</button>

            </div>

            <h2><?php /* @noEscape */ echo __("Actions") ?></h2>
            <div class="fastly-ngwaf-rule-actions">
                <div class="admin__field field _required">
                    <label class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Type") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select id="fastly_ngwaf_rule_action_field" name="fastly_ngwaf_rule_action_field" class="admin__control-text">
                        </select>
                    </div>
                </div>
                <div class="admin__field field _required">
                    <label class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Value") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select id="fastly_ngwaf_rule_action_value" name="fastly_ngwaf_rule_action_value" class="admin__control-text">
                        </select>
                    </div>
                </div>
            </div>
            <div class="fastly-ngwaf-rule-rate-limit-actions">
                <div class="admin__field field _required">
                    <label class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Type") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select id="fastly_ngwaf_rule_rate_limit_action_field"
                                name="fastly_ngwaf_rule_rate_limit_action_field" class="admin__control-text">
                        </select>
                    </div>
                </div>
                <div class="rate-limit-action-value-selection" style="display: flex">
                    <div class="admin__field field _required" style="flex: 1">
                        <label class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Match type") ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select id="fastly_ngwaf_rule_rate_limit_action_match_type"
                                    name="fastly_ngwaf_rule_rate_limit_action_match_type" class="admin__control-text">
                                <option value="RULE-CONDITION" selected>Rule Condition</option>
                                <option value="ALL-REQUESTS">All Requests</option>
                                <option value="OTHER-SIGNAL" data-has-options="true">Other Signal</option>
                            </select>
                        </div>
                    </div>
                    <div class="admin__field field _required rate-limit-action-value-option" style="flex: 1; display: none">
                        <label class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Action signal") ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select id="fastly_ngwaf_rule_rate_limit_action_other_signal_type"
                                    name="fastly_ngwaf_rule_rate_limit_action_other_signal_type" class="admin__control-text">
                            </select>
                        </div>
                    </div>
                </div>

            </div>
            <div class="fastly-ngwaf-rule-rate-limit-details">
                <h2><?php /* @noEscape */ echo __("Rate limiting") ?></h2>
                <div class="admin__field field _required">
                    <h3><?php /* @noEscape */ echo __("Client Identifier") ?></h3>
                    <div class="admin__field-control">
                        <label for="fastly_ngwaf_rule_rate_limit_client_identifier" class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Client Key") ?></span>
                        </label>
                        <select id="fastly_ngwaf_rule_rate_limit_client_identifier"
                                name="fastly_ngwaf_rule_rate_limit_client_identifier" class="admin__control-text">
                        </select>
                    </div>

                    <div class="admin__field field _required fastly-ngwaf-rule-rate-limit-client-identifier-value">
                        <label class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Value") ?></span>
                        </label>
                        <div class="admin__field-control condition-input">
                            <input type="text"
                                   name="fastly_ngwaf_rule_rate_limit_client_identifier_input_value"
                                   required="required"
                                   class="admin__control-text required-entry fastly_ngwaf_rule_rate_limit_client_identifier_value">
                        </div>
                        <div class="admin__field-control condition-select">
                            <select name="fastly_ngwaf_rule_rate_limit_client_identifier_select_value"
                                    class="admin__control-text required-entry fastly_ngwaf_rule_rate_limit_client_identifier_value"
                                    required="required">
                            </select>
                        </div>
                    </div>
                </div>
                <div class="admin__field field _required">
                    <label for="fastly_ngwaf_rule_rate_limit_threshold" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Threshold") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text"
                               name="fastly_ngwaf_rule_rate_limit_threshold"
                               required="required"
                               id="fastly_ngwaf_rule_rate_limit_threshold"
                               class="admin__control-text required-entry">
                    </div>
                </div>
                <div class="admin__field field _required">
                    <label for="fastly_ngwaf_rule_rate_limit_interval" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Interval") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select name="fastly_ngwaf_rule_rate_limit_interval" class="admin__control-text">
                            <option value="60" selected>1 minute</option>
                            <option value="600">10 minutes</option>
                            <option value="3600">60 minutes</option>
                        </select>
                    </div>
                </div>
                <div class="admin__field field _required">
                    <label for="fastly_ngwaf_rule_rate_limit_duration" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Duration") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select name="fastly_ngwaf_rule_rate_limit_duration" class="admin__control-text">
                            <option value="300" selected>5 minutes</option>
                            <option value="3600">1 hour</option>
                            <option value="21600">6 hours</option>
                            <option value="86400">1 day</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="rule-details">
                <h2><?php /* @noEscape */ echo __("Details") ?></h2>
                <div class="admin__field field _required">
                    <label for="fastly_ngwaf_rule_description" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Description") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text"
                               name="fastly_ngwaf_rule_description"
                               required="required"
                               id="fastly_ngwaf_rule_description"
                               class="admin__control-text required-entry">
                    </div>
                </div>
                <div class="admin__field field _required">
                    <label for="fastly_ngwaf_rule_enabled" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Is Rule Enabled") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select name="fastly_ngwaf_rule_rate_limit_duration" class="admin__control-text">
                            <option value="true" selected>Yes</option>
                            <option value="false">No</option>
                        </select>
                    </div>
                </div>
                <div class="rule-request-logging">
                    <div class="admin__field field _required">
                        <label for="fastly_ngwaf_rule_request_logging" class="admin__field-label">
                            <span><?php /* @noEscape */ echo __("Request logging") ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select id="fastly_ngwaf_rule_request_logging" name="fastly_ngwaf_rule_request_logging" class="admin__control-text">
                                <option value="sampled" selected>Sample</option>
                                <option value="none">None</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>


<script type="text/x-magento-init">
    {
        "*": {
            "ngwafRules": {
                "getAllRulesUrl": "<?= $escaper->escapeJs($getRulesUrl);?>",
                "deleteRuleUrl": "<?= $escaper->escapeJs($deleteRuleUrl);?>",
                "editRuleUrl": "<?= $escaper->escapeJs($editRuleUrl);?>",
                "ruleSelectOptionsUrl": "<?= $escaper->escapeJs($getRuleSelectOptionsUrl);?>",
                "rulePayload": <?= $rulePayload?>
            }
        }
    }
</script>

<style>

    .fastly-delete-snippet-icon::before {
        content: '\e630';
        font-size: 2rem;
    }

</style>
